Publish Swift SymbolKit's documentation to GitHub pages
apple/swift-docc-symbolkit pull request #19
Opened 2022-03-20 03:09 UTC by Kyle-Ye

# Summary

This sets the foundation for deploying Swift SymbolKit's documentation to GitHub pages.

- Adds the [Swift-DocC Plugin](https://github.com/apple/swift-docc-plugin) as a dependency of Swift-Markdown.
- Adds a script to simplify deployment of documentation to GitHub pages.
- Adds check-source and test script and fix missing headers.
- Update README docs (Remove some duplication and add a link to the github page).
- Adds pull request template file as other swift-docc related repo.

After merging this PR, we should be able to prepare a gh-pages branch on the main swift-docc-symbolkit repo with no content on it, run the bin/update-gh-pages-documentation-site script and have docs available.

# Dependencies

None.

# Testing

With Swift 5.6, run:
```
swift package --disable-sandbox preview-documentation --target SymbolKit
```
and confirm the Swift-DocC preview works as expected.

# Checklist

Make sure you check off the following items. If they cannot be completed, provide a reason.

- [x] Added tests
- [x] Ran the ./bin/test script and it succeeded
- [x] Updated documentation if necessary

> Most of the content of this PR comes from @ethan-kusters. This is just a port for swift-docc-symbolkit repo.
> See more info here https://github.com/apple/swift-markdown/pull/32

2022-03-20 03:09 UTC, Kyle-Ye commented
@swift-ci please test

2022-03-21 16:39 UTC, ethan-kusters reviewed
This looks great! Thanks so much for putting this together @Kyle-Ye.

I went ahead and used the script you included to deploy to my fork and it looks like everything is working as expected: https://ethan-kusters.github.io/swift-docc-symbolkit/documentation/symbolkit/.

2022-03-21 16:39 UTC, ethan-kusters commented on README.md
> +## Getting Started Using Markup
```suggestion
## Getting Started Using SymbolKit
```

2022-03-21 16:39 UTC, ethan-kusters commented on README.md
> +Please see Swift `SymbolKit`'s [documentation site](https://apple.github.io/swift-docc-symbolkit/documentation/symbolkit/) for more detailed information about the library.
It looks like we generally refer to SymbolKit without code voice in the existing README.

```suggestion
Please see SymbolKit's [documentation site](https://apple.github.io/swift-docc-symbolkit/documentation/symbolkit/) for more detailed information about the library.
```

2022-03-21 16:39 UTC, ethan-kusters commented on README.md
> +Please see Swift `SymbolKit`'s [documentation site](https://apple.github.io/swift-docc-symbolkit/documentation/symbolkit/) for more detailed information about the library.
What do you think of moving this line up directly after:

> In addition, graph representations of data also present opportunities for visualizations in documentation, illustrating the structure or hierarchy of a module.

And before 

> Getting Started Using SymbolKit

?

2022-03-21 16:39 UTC, ethan-kusters commented on bin/test
> +# First get the absolute path to this file so we can get the absolute file path to the SwiftMarkdown root source dir.
```suggestion
# First get the absolute path to this file so we can get the absolute file path to the SymbolKit root source dir.
```

2022-03-21 16:39 UTC, ethan-kusters commented on bin/test
> +# Build SwiftMarkdown.
```suggestion
# Build SymbolKit.
```

2022-03-21 16:39 UTC, ethan-kusters commented on bin/check-source
> +tmp=$(mktemp /tmp/.swift-markdown-check-source_XXXXXX)
```suggestion
tmp=$(mktemp /tmp/.swift-symbolkit-check-source_XXXXXX)
```

2022-03-21 17:15 UTC, Kyle-Ye commented
@swift-ci please test

2022-03-21 17:23 UTC, Kyle-Ye commented
@swift-ci please test

2022-03-21 17:24 UTC, ethan-kusters commented
> By the way, [swift-docc-plugin](https://github.com/apple/swift-docc-plugin/blob/main/Package.swift) has a dependency on main branch of swift-docc-symbolkit. Would it consider to be a circle reference?

That is a _great_ question... Let me check.

2022-03-21 17:25 UTC, Kyle-Ye commented
@swift-ci please test macOS

2022-03-21 21:36 UTC, ethan-kusters commented
@swift-ci please test macOS

2022-03-21 21:56 UTC, ethan-kusters commented
@swift-ci please test

2022-03-21 23:43 UTC, ethan-kusters commented
> > By the way, [swift-docc-plugin](https://github.com/apple/swift-docc-plugin/blob/main/Package.swift) has a dependency on main branch of swift-docc-symbolkit. Would it consider to be a circle reference?
> 
> That is a _great_ question... Let me check.

It looks like it does:

```
% swift build
Fetching https://github.com/apple/swift-docc-plugin from cache
Fetched https://github.com/apple/swift-docc-plugin (0.42s)
Creating working copy for https://github.com/apple/swift-docc-plugin
Working copy of https://github.com/apple/swift-docc-plugin resolved at main
error: cyclic dependency declaration found: SymbolKit -> SwiftDocCPlugin -> SymbolKit
```

Hm. I think we'll need to figure out a workaround here... It might be we just need to add a custom script for building documentation instead of using the plugin. I'm intentionally trying to keep the number of dependencies the plugin has a to a minimum for this exact reason but SymbolKit is unavoidable at the moment.

2022-03-21 23:43 UTC, ethan-kusters requested changes
Unfortunately I don't think we can land this as-is since it will introduce a cyclic dependency with the Swift-DocC Plugin.

2022-03-22 03:30 UTC, Kyle-Ye commented
> Unfortunately I don't think we can land this as-is since it will introduce a cyclic dependency with the Swift-DocC Plugin.

Got it, seems like the dependency was introduced 3 days ago by https://github.com/apple/swift-docc-plugin/pull/7.

So there is 2 ways to solve this:
1. Remove SymbolKit dependency on Swift-Docc Plugin. (I think "Swift-Docc Plugin" is a basic plugin and should not depends on "SymbolKit")
2. Change the PR to use a new script instead of using Swift-Docc Plugin which causes a duplication and potential inconsistency.

Personally I prefer way 1, but way 2 is acceptable for me. Can I get your suggestion on this? @ethan-kusters

2022-03-22 17:20 UTC, ethan-kusters commented
> > Unfortunately I don't think we can land this as-is since it will introduce a cyclic dependency with the Swift-DocC Plugin.
> 
> Got it, seems like the dependency was introduced 3 days ago by [apple/swift-docc-plugin#7](https://github.com/apple/swift-docc-plugin/pull/7).
> 
> So there is 2 ways to solve this:
> 
> 1. Remove SymbolKit dependency on Swift-Docc Plugin. (I think "Swift-Docc Plugin" is a basic plugin and should not depends on "SymbolKit")
> 2. Change the PR to use a new script instead of using Swift-Docc Plugin which causes a duplication and potential inconsistency.
> 
> Personally I prefer way 1, but way 2 is acceptable for me. Can I get your suggestion on this? @ethan-kusters cc @bitjammer

@bitjammer can speak to this more but my understanding is in the longer-term we'd like to move the new `snippet-build` executable to a separate repository so it can be used by more projects than just the `swift-docc-plugin` but, for now, the plugin is the place where it makes the most sense.

So I think we should plan on using a custom script instead of the Swift-DocC Plugin for now but plan on removing it and adopting the Plugin as soon as it becomes possible.

I've written a couple of similar scripts before, so I'm happy to open a PR against your branch later today to add the basis for something and we can iterate on it there.

2022-03-22 21:36 UTC, bitjammer commented
So unfortunately, moving the tool to a new repo will not solve the dependency problem as SwiftPM plugins share their dependency graph with their clients. This is not an intentional limitation and ought to be fixed but I don't see it happening very soon. We can't remove the dependency on SymbolKit because we use the Symbol Graph model to communicate snippet information to DocC. I'm seeing what my options are for deploying the tool elsewhere but if we can have this one exception in the meantime, I would appreciate it!

2022-03-23 00:04 UTC, ethan-kusters commented
@Kyle-Ye I've opened a PR against your branch here with a script as a temporary workaround until we resolve these issues with the plugin: https://github.com/Kyle-Ye/swift-docc-symbolkit/pull/1/files.

2022-03-23 12:51 UTC, Kyle-Ye commented
@swift-ci please test

2022-03-23 16:54 UTC, merged

2022-03-23 16:57 UTC, Kyle-Ye commented
The doc page is currently unavailable https://apple.github.io/swift-docc-symbolkit/documentation/symbolkit/

Seems that we need to create/enable the some environment like the following.
<img width="340" alt="截屏2022-03-24 00 56 27" src="https://user-images.githubusercontent.com/43724855/159754260-8fd6f298-89ae-4a73-9085-a57c0a695048.png">

cc @franklinsch

2022-03-23 17:02 UTC, franklinsch commented
It's live now: https://apple.github.io/swift-docc-symbolkit/documentation/symbolkit. Thanks for the amazing work here once again @Kyle-Ye 🚀